name: emacs-pylsp
channels:
 - conda-forge
dependencies:
 - python-lsp-server
 - rope
 - pyflakes
 - mccabe
 - pycodestyle
 - pydocstyle
 - flake8
 - pylint
 - pylsp-mypy
 - pyls-isort
 - python-lsp-black
 - python-lsp-ruff
 - fortls
